### ISSUE TITLE
Looks like save_progress and save_every are not working in v0.6.2

### ISSUE THREAD

**Issue by ibeltagy** [lmjohns3/theanets#87]
In v0.5.3, I used to use: 
exp = theanets.Experiment(theanets.Classifier, layers= ... , save_progress=path, save_every=int)
which loads a saved model (if exists), then saves the new trained model every couple of minutes. 

In v0.6.2, I get "an unexpected keyword argument 'save_every' ". I can still pass the two arguments to the function: 
exp.train()
which successfully saves the model every couple of minutes, but it does not load the saved model.

**Comment by lmjohns3** [comment]
Yes, the kwargs API changed a bit in the v0.6.x releases -- I figured it wouldn't be too difficult to move the training-specific args to the train method call. To load the model automatically, pass the path to the Experiment constructor:

    exp = theanets.Experiment(path)
    exp.train(save_progress=path, save_every=5)

**Comment by lmjohns3** [comment]
I'm going to close this issue, please reopen if you think it needs fixing.
