### ISSUE TITLE
Can't deserialize Regressor networks: AttributeError: 'Regressor' object has no attribute '_functions' as of 33775e7c96

### ISSUE THREAD

**Issue by abramhindle** [lmjohns3/theanets#91]
Given this source code https://gist.github.com/abramhindle/71e3dd1d37363851c80b , the last line doesn't succeed because of I assume failed deserialization with commit 33775e7c96 : 

    I 2015-08-04 06:14:39 downhill.base:226 RProp 6860 loss=0.000000 err=0.000000
    I 2015-08-04 06:14:39 downhill.base:226 validation 686 loss=0.000000 err=0.000000
    I 2015-08-04 06:14:39 downhill.base:402 patience elapsed!
    I 2015-08-04 06:14:39 root:19 Input:
    [[ 0.  0.]
     [ 0.  1.]
     [ 1.  0.]
     [ 1.  1.]]
    I 2015-08-04 06:14:39 root:20 XOR output:
    [[ 0.]
     [ 1.]
     [ 1.]
     [ 0.]]
    I 2015-08-04 06:14:41 root:21 NN XOR predictions:
    [[-0.]
     [ 1.]
     [ 1.]
     [ 0.]]
    I 2015-08-04 06:14:41 theanets.graph:574 xor-net-save: saved model
    I 2015-08-04 06:14:41 theanets.graph:591 xor-net-save: loaded model
    Traceback (most recent call last):
      File "save-dont-work.py", line 25, in <module>
        logging.info("Saved NN XOR predictions:\n%s", netsaved.predict(X.astype('f')).round(2))
      File "build/bdist.linux-x86_64/egg/theanets/graph.py", line 526, in predict
      File "build/bdist.linux-x86_64/egg/theanets/graph.py", line 501, in feed_forward
    AttributeError: 'Regressor' object has no attribute '_functions'

    ubuntu@85f9ed3c985d:~/deep-learning/theanets$ git log HEAD
    commit 33775e7c96adbe2924cadb13f0061fd648a74c46
    Author: Leif Johnson <leif@lmjohns3.com>
    Date:   Mon Aug 3 13:08:11 2015 -0500
    
        Add a loss for maximum mean discrepancy.

    ubuntu@85f9ed3c985d:~/deep-learning/theanets$ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.2 LTS
    Release:	14.04
    Codename:	trusty

No GPU. CPU only.

    ubuntu@85f9ed3c985d:~/deep-learning$ pip install theanets
    Requirement already satisfied (use --upgrade to upgrade): theanets in /usr/local/lib/python2.7/dist-packages/theanets-0.7.0pre-py2.7.egg
    Requirement already satisfied (use --upgrade to upgrade): climate in /usr/local/lib/python2.7/dist-packages (from theanets)
    Requirement already satisfied (use --upgrade to upgrade): downhill in /usr/local/lib/python2.7/dist-packages (from theanets)
    Requirement already satisfied (use --upgrade to upgrade): theano in /usr/local/lib/python2.7/dist-packages (from theanets)
    Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.2 in /usr/lib/python2.7/dist-packages (from theano->theanets)
    Requirement already satisfied (use --upgrade to upgrade): scipy>=0.11 in /usr/lib/python2.7/dist-packages (from theano->theanets)
    Cleaning up...

**Comment by abramhindle** [comment]
It seems to load if I set

    net._graphs = {}
    net._functions = {}

before I run predict. But I ask the developers, does it matter if _graphs and _functions are empty dicts?

**Comment by lmjohns3** [comment]
Thanks for the bug report! I think I've committed a fix for this. Please reopen if you continue to get this problem.
